
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.16.2
 * Query Engine version: 1c57fdcd7e44b29b9313256c76699e91c3ac3c43
 */
Prisma.prismaVersion = {
  client: "6.16.2",
  engine: "1c57fdcd7e44b29b9313256c76699e91c3ac3c43"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  username: 'username',
  passwordHash: 'passwordHash',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AuditLogScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  actorUsername: 'actorUsername',
  action: 'action',
  entityType: 'entityType',
  entityId: 'entityId',
  summary: 'summary',
  metadata: 'metadata',
  createdAt: 'createdAt'
};

exports.Prisma.CharacterScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  background: 'background',
  originCulture: 'originCulture',
  originSystem: 'originSystem',
  upbringing: 'upbringing',
  concept: 'concept',
  groupConcept: 'groupConcept',
  icon: 'icon',
  reputation: 'reputation',
  personalProblem: 'personalProblem',
  face: 'face',
  clothing: 'clothing',
  portraitPath: 'portraitPath',
  strength: 'strength',
  agility: 'agility',
  wits: 'wits',
  empathy: 'empathy',
  maxHitPoints: 'maxHitPoints',
  currentHitPoints: 'currentHitPoints',
  maxMindPoints: 'maxMindPoints',
  currentMindPoints: 'currentMindPoints',
  maxRadiation: 'maxRadiation',
  radiation: 'radiation',
  experience: 'experience',
  criticalInjuries: 'criticalInjuries',
  notes: 'notes',
  myCabinDescription: 'myCabinDescription',
  myCabinGear: 'myCabinGear',
  myCabinOther: 'myCabinOther',
  birr: 'birr',
  armorName: 'armorName',
  armorRating: 'armorRating',
  armorComment: 'armorComment',
  dexterity: 'dexterity',
  force: 'force',
  infiltration: 'infiltration',
  manipulation: 'manipulation',
  meleeCombat: 'meleeCombat',
  observation: 'observation',
  rangedCombat: 'rangedCombat',
  survival: 'survival',
  command: 'command',
  culture: 'culture',
  dataDjinn: 'dataDjinn',
  medicurgy: 'medicurgy',
  mysticPowers: 'mysticPowers',
  pilot: 'pilot',
  science: 'science',
  technology: 'technology',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CharacterConditionModifierScalarFieldEnum = {
  id: 'id',
  characterId: 'characterId',
  order: 'order',
  target: 'target',
  name: 'name',
  description: 'description',
  value: 'value',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CharacterPortraitScalarFieldEnum = {
  characterId: 'characterId',
  mimeType: 'mimeType',
  data: 'data',
  updatedAt: 'updatedAt'
};

exports.Prisma.TeamScalarFieldEnum = {
  id: 'id',
  name: 'name',
  manifesto: 'manifesto',
  story: 'story',
  groupConcept: 'groupConcept',
  groupTalent: 'groupTalent',
  patron: 'patron',
  nemesis: 'nemesis',
  shipName: 'shipName',
  shipType: 'shipType',
  shipClass: 'shipClass',
  shipProblem: 'shipProblem',
  shipDebt: 'shipDebt',
  shipUpgrades: 'shipUpgrades',
  currentGoal: 'currentGoal',
  nextLead: 'nextLead',
  reward: 'reward',
  deadline: 'deadline',
  unresolvedMystery: 'unresolvedMystery',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TeamCrewPositionScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  order: 'order',
  role: 'role',
  primaryCharacterId: 'primaryCharacterId',
  backupCharacterId: 'backupCharacterId',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TeamStoryBeatScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  parentBeatId: 'parentBeatId',
  order: 'order',
  title: 'title',
  description: 'description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TeamNoteScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  order: 'order',
  tag: 'tag',
  title: 'title',
  body: 'body',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TeamKnownFaceScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  order: 'order',
  name: 'name',
  concept: 'concept',
  faction: 'faction',
  lastSeen: 'lastSeen',
  trustLevel: 'trustLevel',
  notes: 'notes',
  portraitPath: 'portraitPath',
  promotedCharacterId: 'promotedCharacterId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TeamKnownFacePortraitScalarFieldEnum = {
  knownFaceId: 'knownFaceId',
  mimeType: 'mimeType',
  data: 'data',
  updatedAt: 'updatedAt'
};

exports.Prisma.TeamFactionTieScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  order: 'order',
  faction: 'faction',
  stance: 'stance',
  heat: 'heat',
  leverageHolder: 'leverageHolder',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CharacterRelationshipScalarFieldEnum = {
  id: 'id',
  characterId: 'characterId',
  order: 'order',
  targetName: 'targetName',
  description: 'description',
  isBuddy: 'isBuddy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CharacterTalentScalarFieldEnum = {
  id: 'id',
  characterId: 'characterId',
  order: 'order',
  name: 'name',
  source: 'source',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CharacterWeaponScalarFieldEnum = {
  id: 'id',
  characterId: 'characterId',
  order: 'order',
  presetId: 'presetId',
  name: 'name',
  bonus: 'bonus',
  initiative: 'initiative',
  damage: 'damage',
  crit: 'crit',
  range: 'range',
  comments: 'comments',
  reloads: 'reloads',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CharacterGearItemScalarFieldEnum = {
  id: 'id',
  characterId: 'characterId',
  order: 'order',
  presetId: 'presetId',
  name: 'name',
  bonus: 'bonus',
  comment: 'comment',
  quantity: 'quantity',
  encumbranceUnits: 'encumbranceUnits',
  isTiny: 'isTiny',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CharacterContactScalarFieldEnum = {
  id: 'id',
  characterId: 'characterId',
  order: 'order',
  name: 'name',
  concept: 'concept',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.OriginCulture = exports.$Enums.OriginCulture = {
  firstcome: 'firstcome',
  zenithian: 'zenithian'
};

exports.OriginSystem = exports.$Enums.OriginSystem = {
  algol: 'algol',
  mira: 'mira',
  kua: 'kua',
  dabaran: 'dabaran',
  zalos: 'zalos',
  other: 'other'
};

exports.Upbringing = exports.$Enums.Upbringing = {
  plebeian: 'plebeian',
  stationary: 'stationary',
  privileged: 'privileged'
};

exports.ConditionModifierTarget = exports.$Enums.ConditionModifierTarget = {
  hitPoints: 'hitPoints',
  mindPoints: 'mindPoints',
  radiation: 'radiation'
};

exports.TeamCrewRole = exports.$Enums.TeamCrewRole = {
  captain: 'captain',
  engineer: 'engineer',
  pilot: 'pilot',
  sensorOperator: 'sensorOperator',
  gunner: 'gunner'
};

exports.TeamNoteTag = exports.$Enums.TeamNoteTag = {
  mission: 'mission',
  npc: 'npc',
  faction: 'faction',
  ship: 'ship',
  mystery: 'mystery',
  debt: 'debt',
  session: 'session'
};

exports.TeamFactionStance = exports.$Enums.TeamFactionStance = {
  ally: 'ally',
  neutral: 'neutral',
  enemy: 'enemy'
};

exports.TalentSource = exports.$Enums.TalentSource = {
  group: 'group',
  concept: 'concept',
  icon: 'icon',
  other: 'other'
};

exports.Prisma.ModelName = {
  User: 'User',
  AuditLog: 'AuditLog',
  Character: 'Character',
  CharacterConditionModifier: 'CharacterConditionModifier',
  CharacterPortrait: 'CharacterPortrait',
  Team: 'Team',
  TeamCrewPosition: 'TeamCrewPosition',
  TeamStoryBeat: 'TeamStoryBeat',
  TeamNote: 'TeamNote',
  TeamKnownFace: 'TeamKnownFace',
  TeamKnownFacePortrait: 'TeamKnownFacePortrait',
  TeamFactionTie: 'TeamFactionTie',
  CharacterRelationship: 'CharacterRelationship',
  CharacterTalent: 'CharacterTalent',
  CharacterWeapon: 'CharacterWeapon',
  CharacterGearItem: 'CharacterGearItem',
  CharacterContact: 'CharacterContact'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
