import type { InventoryPreset } from "@/lib/roster-types";

export const inventoryCatalog: InventoryPreset[] = [
  {
    id: "custom-weapon",
    kind: "weapon",
    label: "Custom weapon",
    category: "Flexible",
    bonus: 0,
    initiative: 0,
    damage: 0,
    crit: "",
    range: "",
    comments: "Fill in the weapon details.",
    reloads: 0,
  },
  {
    id: "custom-gear",
    kind: "gear",
    label: "Custom gear",
    category: "Flexible",
    bonus: "",
    comment: "Describe the item freely.",
    encumbranceUnits: 2,
  },
  {
    id: "custom-tiny",
    kind: "tiny",
    label: "Custom tiny item",
    category: "Flexible",
    bonus: "",
    comment: "Pocket-sized or symbolic item.",
    encumbranceUnits: 0,
  },
  {
    id: "vulcan-cricket",
    kind: "weapon",
    label: "Vulcan cricket",
    category: "Sidearms",
    bonus: 1,
    initiative: 2,
    damage: 2,
    crit: "2",
    range: "Short",
    comments: "Light",
    reloads: 1,
  },
  {
    id: "stun-gun",
    kind: "weapon",
    label: "Stun gun",
    category: "Sidearms",
    bonus: 1,
    initiative: 1,
    damage: 2,
    crit: "Stun",
    range: "Short",
    comments: "Stun",
    reloads: 1,
  },
  {
    id: "accelerator-pistol",
    kind: "weapon",
    label: "Accelerator pistol",
    category: "Sidearms",
    bonus: 1,
    initiative: 0,
    damage: 2,
    crit: "1",
    range: "Long",
    comments: "Silent",
    reloads: 1,
  },
  {
    id: "vulcan-carbine",
    kind: "weapon",
    label: "Vulcan carbine",
    category: "Carbines",
    bonus: 1,
    initiative: 0,
    damage: 3,
    crit: "2",
    range: "Short",
    comments: "Automatic fire",
    reloads: 2,
  },
  {
    id: "vulcan-carbine-sensor-scope",
    kind: "weapon",
    label: "Vulcan carbine with sensor scope",
    category: "Carbines",
    bonus: 1,
    initiative: 0,
    damage: 3,
    crit: "2",
    range: "Short",
    comments: "Automatic fire, sensor scope",
    reloads: 2,
  },
  {
    id: "dura-sword",
    kind: "weapon",
    label: "Dura sword",
    category: "Melee",
    bonus: 1,
    initiative: 0,
    damage: 2,
    crit: "1",
    range: "Close",
    comments: "Heavy, cell-powered",
    reloads: 0,
  },
  {
    id: "mercurium-dagger",
    kind: "weapon",
    label: "Mercurium dagger",
    category: "Melee",
    bonus: 1,
    initiative: 1,
    damage: 3,
    crit: "2",
    range: "Close",
    comments: "Light, mercurium, cell-powered",
    reloads: 0,
  },
  {
    id: "mercurium-sword",
    kind: "weapon",
    label: "Mercurium sword",
    category: "Melee",
    bonus: 2,
    initiative: 0,
    damage: 3,
    crit: "2",
    range: "Close",
    comments: "Light, mercurium, cell-powered",
    reloads: 0,
  },
  {
    id: "dura-axe",
    kind: "weapon",
    label: "Dura axe",
    category: "Melee",
    bonus: 0,
    initiative: 0,
    damage: 3,
    crit: "1",
    range: "Close",
    comments: "Heavy, cell-powered",
    reloads: 0,
  },
  {
    id: "dura-knife",
    kind: "weapon",
    label: "Dura knife",
    category: "Melee",
    bonus: 0,
    initiative: 1,
    damage: 2,
    crit: "1",
    range: "Close",
    comments: "Light, cell-powered",
    reloads: 0,
  },
  {
    id: "advanced-melee-weapon",
    kind: "weapon",
    label: "Advanced melee weapon",
    category: "Melee",
    bonus: 1,
    initiative: 0,
    damage: 3,
    crit: "2",
    range: "Close",
    comments: "Specify the weapon name and mods.",
    reloads: 0,
  },
  {
    id: "frag-grenade",
    kind: "weapon",
    label: "Frag grenade",
    category: "Thrown",
    bonus: 0,
    initiative: 0,
    damage: 2,
    crit: "2",
    range: "Short",
    comments: "Thrown explosive",
    reloads: 1,
  },
  {
    id: "hand-fan",
    kind: "tiny",
    label: "Hand fan",
    category: "Artist",
    bonus: "",
    comment: "Expressive prop",
    encumbranceUnits: 0,
  },
  {
    id: "tabula",
    kind: "gear",
    label: "Tabula",
    category: "Utility",
    bonus: "",
    comment: "Mimetic-glass tablet",
    encumbranceUnits: 1,
  },
  {
    id: "opor",
    kind: "tiny",
    label: "Opor",
    category: "Artist",
    bonus: "",
    comment: "Scented luxury item",
    encumbranceUnits: 0,
  },
  {
    id: "environment-scanner",
    kind: "gear",
    label: "Environment scanner",
    category: "Utility",
    bonus: "",
    comment: "Survey local atmosphere and hazards",
    encumbranceUnits: 1,
  },
  {
    id: "exquisite-clothing",
    kind: "gear",
    label: "Exquisite clothing",
    category: "Wardrobe",
    bonus: "",
    comment: "Ceremonial or high-status dress",
    encumbranceUnits: 0,
  },
  {
    id: "musical-instrument",
    kind: "gear",
    label: "Musical instrument",
    category: "Artist",
    bonus: "",
    comment: "Portable performance instrument",
    encumbranceUnits: 2,
  },
  {
    id: "beautiful-bio",
    kind: "gear",
    label: "Beautiful (BIO)",
    category: "Artist",
    bonus: "+1 first impression",
    comment: "Cosmetic biosculpting upgrade",
    encumbranceUnits: 0,
  },
  {
    id: "rare-poems",
    kind: "gear",
    label: "Rare collection of poems",
    category: "Artist",
    bonus: "",
    comment: "Beloved anthology",
    encumbranceUnits: 1,
  },
  {
    id: "standing-reservation",
    kind: "tiny",
    label: "Standing reservation",
    category: "Artist",
    bonus: "",
    comment: "Prestige booking on Coriolis",
    encumbranceUnits: 0,
  },
  {
    id: "communicator-ii",
    kind: "gear",
    label: "Communicator (II)",
    category: "Comms",
    bonus: "",
    comment: "Short-range communicator",
    encumbranceUnits: 1,
  },
  {
    id: "communicator-iii",
    kind: "gear",
    label: "Communicator (III)",
    category: "Comms",
    bonus: "",
    comment: "Reliable personal communicator",
    encumbranceUnits: 1,
  },
  {
    id: "communicator-iv",
    kind: "gear",
    label: "Communicator (IV)",
    category: "Comms",
    bonus: "",
    comment: "Orbit-range communicator",
    encumbranceUnits: 4,
  },
  {
    id: "communicator-v",
    kind: "gear",
    label: "Communicator (V)",
    category: "Comms",
    bonus: "",
    comment: "System-range communicator",
    encumbranceUnits: 4,
  },
  {
    id: "com-link-v",
    kind: "gear",
    label: "Com link V",
    category: "Comms",
    bonus: "",
    comment: "System-range comm-link hardware",
    encumbranceUnits: 4,
  },
  {
    id: "personal-holograph",
    kind: "gear",
    label: "Personal holograph",
    category: "Data Spider",
    bonus: "",
    comment: "Portable holographic display",
    encumbranceUnits: 0,
  },
  {
    id: "proximity-sensor",
    kind: "gear",
    label: "Proximity sensor",
    category: "Sensors",
    bonus: "",
    comment: "Warns about nearby movement",
    encumbranceUnits: 2,
  },
  {
    id: "computer",
    kind: "gear",
    label: "Computer",
    category: "Utility",
    bonus: "",
    comment: "Portable computing rig",
    encumbranceUnits: 2,
  },
  {
    id: "transactor-1000",
    kind: "tiny",
    label: "Transactor with 1,000 birr",
    category: "Finance",
    bonus: "",
    comment: "Biocode-locked spending account",
    encumbranceUnits: 0,
  },
  {
    id: "tag-500",
    kind: "tiny",
    label: "Tag with 500 birr",
    category: "Finance",
    bonus: "",
    comment: "Anonymous spending tag",
    encumbranceUnits: 0,
  },
  {
    id: "anonymous-clothing",
    kind: "gear",
    label: "Anonymous clothing",
    category: "Fugitive",
    bonus: "",
    comment: "Forgettable, low-profile layers",
    encumbranceUnits: 0,
  },
  {
    id: "protective-clothing",
    kind: "gear",
    label: "Protective clothing",
    category: "Armor",
    bonus: "",
    comment: "Low-profile protection",
    encumbranceUnits: 1,
  },
  {
    id: "thermostatic-suit",
    kind: "gear",
    label: "Thermostatic suit",
    category: "Survival",
    bonus: "",
    comment: "Stabilizes body temperature",
    encumbranceUnits: 2,
  },
  {
    id: "exo-shell",
    kind: "gear",
    label: "Exo shell",
    category: "Survival",
    bonus: "",
    comment: "Vacuum and hostile-environment protection",
    encumbranceUnits: 4,
  },
  {
    id: "mask",
    kind: "tiny",
    label: "Mask",
    category: "Fugitive",
    bonus: "",
    comment: "Conceal identity",
    encumbranceUnits: 0,
  },
  {
    id: "language-modulator",
    kind: "tiny",
    label: "Language modulator (CYB)",
    category: "Negotiator",
    bonus: "",
    comment: "Speech adaptation implant",
    encumbranceUnits: 0,
  },
  {
    id: "voice-amplifier",
    kind: "gear",
    label: "Voice amplifier",
    category: "Negotiator",
    bonus: "",
    comment: "Project authority across a room",
    encumbranceUnits: 1,
  },
  {
    id: "kambra",
    kind: "tiny",
    label: "Kambra (D6 doses)",
    category: "Negotiator",
    bonus: "",
    comment: "Luxury stimulant doses",
    encumbranceUnits: 0,
  },
  {
    id: "lie-detector",
    kind: "tiny",
    label: "Lie detector (CYB)",
    category: "Negotiator",
    bonus: "",
    comment: "Subtle biometric tell-reader",
    encumbranceUnits: 0,
  },
  {
    id: "language-unit",
    kind: "tiny",
    label: "Language unit",
    category: "Negotiator",
    bonus: "",
    comment: "Portable translation support",
    encumbranceUnits: 0,
  },
  {
    id: "modulation-mask",
    kind: "gear",
    label: "Modulation mask",
    category: "Operative",
    bonus: "",
    comment: "Projects a synthetic disguise",
    encumbranceUnits: 1,
  },
  {
    id: "mechanical-lockpick",
    kind: "gear",
    label: "Mechanical lockpick",
    category: "Operative",
    bonus: "",
    comment: "Manual bypass for old locks",
    encumbranceUnits: 1,
  },
  {
    id: "fake-identities",
    kind: "gear",
    label: "An assortment of fake identities",
    category: "Operative",
    bonus: "",
    comment: "False credentials, tags, and papers",
    encumbranceUnits: 0,
  },
  {
    id: "security-tablet",
    kind: "gear",
    label: "Security tablet",
    category: "Operative",
    bonus: "",
    comment: "Security control and bypass slate",
    encumbranceUnits: 1,
  },
  {
    id: "poison-5-doses",
    kind: "tiny",
    label: "Poison (5 doses)",
    category: "Operative",
    bonus: "",
    comment: "A compact dose set for covert work",
    encumbranceUnits: 0,
  },
  {
    id: "tools-ordinary",
    kind: "gear",
    label: "Tools (Ordinary)",
    category: "Technical",
    bonus: "",
    comment: "Standard work kit",
    encumbranceUnits: 2,
  },
  {
    id: "tools-advanced",
    kind: "gear",
    label: "Tools (Advanced)",
    category: "Technical",
    bonus: "+1 technology",
    comment: "Advanced repair and diagnostic kit",
    encumbranceUnits: 1,
  },
  {
    id: "pilot-talisman",
    kind: "tiny",
    label: "Talisman (Pilot +1)",
    category: "Pilot",
    bonus: "Pilot +1",
    comment: "Lucky icon or reliquary",
    encumbranceUnits: 0,
  },
  {
    id: "hand-jet",
    kind: "gear",
    label: "Hand jet",
    category: "Pilot",
    bonus: "",
    comment: "Zero-G maneuver tool",
    encumbranceUnits: 1,
  },
  {
    id: "targeting-scope",
    kind: "tiny",
    label: "Targeting scope (CYB)",
    category: "Pilot",
    bonus: "",
    comment: "Aimed fire support optic",
    encumbranceUnits: 0,
  },
  {
    id: "flight-suit",
    kind: "gear",
    label: "Flight suit",
    category: "Pilot",
    bonus: "",
    comment: "Pilot-rated pressure layers",
    encumbranceUnits: 1,
  },
  {
    id: "blessed-scripture",
    kind: "tiny",
    label: "Blessed scripture",
    category: "Preacher",
    bonus: "",
    comment: "Portable holy text",
    encumbranceUnits: 0,
  },
  {
    id: "thurible",
    kind: "tiny",
    label: "Thurible",
    category: "Preacher",
    bonus: "",
    comment: "Incense burner",
    encumbranceUnits: 0,
  },
  {
    id: "talisman",
    kind: "tiny",
    label: "Talisman",
    category: "Preacher",
    bonus: "",
    comment: "Protective icon or charm",
    encumbranceUnits: 0,
  },
  {
    id: "casula",
    kind: "gear",
    label: "Cásula (preacher's robes)",
    category: "Preacher",
    bonus: "",
    comment: "Formal clerical robes",
    encumbranceUnits: 0,
  },
  {
    id: "reliquary",
    kind: "tiny",
    label: "Reliquary",
    category: "Preacher",
    bonus: "",
    comment: "Holy keepsake",
    encumbranceUnits: 0,
  },
  {
    id: "written-prophecy",
    kind: "tiny",
    label: "Written prophecy",
    category: "Preacher",
    bonus: "",
    comment: "Personal omen or revelation",
    encumbranceUnits: 0,
  },
  {
    id: "blessed-m-doses",
    kind: "tiny",
    label: "10 blessed m-doses",
    category: "Preacher",
    bonus: "",
    comment: "Blessed medicurgy doses",
    encumbranceUnits: 0,
  },
  {
    id: "herbal-remedies",
    kind: "tiny",
    label: "10 herbal remedies",
    category: "Preacher",
    bonus: "",
    comment: "Traditional medicine kit",
    encumbranceUnits: 0,
  },
  {
    id: "writing-paraphernalia",
    kind: "tiny",
    label: "Writing paraphernalia",
    category: "Preacher",
    bonus: "",
    comment: "Ink, stylus, and vellum",
    encumbranceUnits: 0,
  },
  {
    id: "portable-lab",
    kind: "gear",
    label: "Portable lab",
    category: "Scientist",
    bonus: "",
    comment: "Field analysis kit",
    encumbranceUnits: 4,
  },
  {
    id: "database",
    kind: "gear",
    label: "Database",
    category: "Scientist",
    bonus: "",
    comment: "Portable library database and reference archive",
    encumbranceUnits: 0,
  },
  {
    id: "pressure-tent",
    kind: "gear",
    label: "Pressure tent",
    category: "Scientist",
    bonus: "",
    comment: "Field shelter for hostile worlds",
    encumbranceUnits: 4,
  },
  {
    id: "medkit",
    kind: "gear",
    label: "Medkit",
    category: "Scientist",
    bonus: "",
    comment: "Portable emergency medicurgy",
    encumbranceUnits: 2,
  },
  {
    id: "vacuum-sealer",
    kind: "gear",
    label: "Vacuum sealer",
    category: "Ship Worker",
    bonus: "",
    comment: "Patch exos and hull pinholes",
    encumbranceUnits: 1,
  },
  {
    id: "power-glove",
    kind: "gear",
    label: "Power glove",
    category: "Ship Worker",
    bonus: "",
    comment: "Heavy-duty work glove",
    encumbranceUnits: 1,
  },
  {
    id: "arrash",
    kind: "tiny",
    label: "Arrash",
    category: "Ship Worker",
    bonus: "",
    comment: "Comfort item from the docks",
    encumbranceUnits: 0,
  },
  {
    id: "tabak",
    kind: "tiny",
    label: "Tabak",
    category: "Ship Worker",
    bonus: "",
    comment: "Personal vice",
    encumbranceUnits: 0,
  },
  {
    id: "exo-loader",
    kind: "gear",
    label: "Exo loader",
    category: "Ship Worker",
    bonus: "",
    comment: "Industrial lifting exo",
    encumbranceUnits: 4,
  },
  {
    id: "hyper-rope",
    kind: "gear",
    label: "Hyper rope",
    category: "Ship Worker",
    bonus: "",
    comment: "Tough multipurpose cable",
    encumbranceUnits: 0,
  },
  {
    id: "heavy-armor",
    kind: "gear",
    label: "Heavy armor",
    category: "Armor",
    bonus: "",
    comment: "Serious battlefield protection",
    encumbranceUnits: 4,
  },
  {
    id: "cybernetic-muscles",
    kind: "tiny",
    label: "Cybernetic muscles (CYB)",
    category: "Soldier",
    bonus: "",
    comment: "Augmented physical power",
    encumbranceUnits: 0,
  },
  {
    id: "command-unit",
    kind: "gear",
    label: "Command unit",
    category: "Soldier",
    bonus: "",
    comment: "Officer's tactical command rig",
    encumbranceUnits: 1,
  },
  {
    id: "advanced-scope",
    kind: "tiny",
    label: "Advanced scope",
    category: "Soldier",
    bonus: "+1 ranged combat",
    comment: "Advanced target optic",
    encumbranceUnits: 0,
  },
  {
    id: "recon-drone",
    kind: "gear",
    label: "Recon drone",
    category: "Trailblazer",
    bonus: "",
    comment: "Remote scouting support",
    encumbranceUnits: 2,
  },
  {
    id: "m-doses",
    kind: "tiny",
    label: "5 m-doses",
    category: "Trailblazer",
    bonus: "",
    comment: "Medicurgy doses",
    encumbranceUnits: 0,
  },
  {
    id: "weatherproof",
    kind: "tiny",
    label: "Weatherproof (CYB)",
    category: "Trailblazer",
    bonus: "",
    comment: "Adaptive weather hardening",
    encumbranceUnits: 0,
  },
  {
    id: "compass",
    kind: "tiny",
    label: "Compass",
    category: "Trailblazer",
    bonus: "",
    comment: "Backups never hurt",
    encumbranceUnits: 0,
  },
  {
    id: "armor-piercing-ammo",
    kind: "tiny",
    label: "Armor-piercing ammo",
    category: "Supplies",
    bonus: "",
    comment: "Specialized ammunition",
    encumbranceUnits: 0,
  },
  {
    id: "spare-reload",
    kind: "tiny",
    label: "Spare reload",
    category: "Supplies",
    bonus: "",
    comment: "Extra magazine or power cell",
    encumbranceUnits: 0,
  },
];
